<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lesson 60. Javascript 101</title>
    <link rel="stylesheet" href="/css/styles.css">
</head>
<body>
<h1>Содержимое страницы</h1>

<form id="post-form" name="form" enctype="multipart/form-data">
    <input type="file" name="images">
    <input type="text" placeholder="Description" name="description">
    <button type="button" id="save-post">Отправить</button>
</form>
</body>
</html>

<script src="/js/post.js"></script>
