<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Lesson 62. Registration</title>
        <link rel="stylesheet" href="/css/styles.css">
    </head>
    <body>

        <!-- Splash screen -->
        <section id="page-splash" class="page-splash">
            <div class="d-flex justify-content-center">
                <div class="mx-3">
                    <h3>Регистрация</h3>
                    <form id="registration-form">
                        <input type="email" name="email" class="form-control mb-1" placeholder="Email"><br>
                        <input type="text" name="name" class="form-control mb-1" placeholder="Полное имя"><br>
                        <input type="text" name="login" class="form-control mb-1" placeholder="Логин"><br>
                        <input type="password" name="password" class="form-control mb-1" placeholder="Пароль"><br>
                        <button class="btn btn-outline-primary btn-block">Зарегистрироваться</button>
                    </form>
                </div>
            </div>

        </section>
    </body>
</html>

<script src="/js/reg.js"></script>
